import { AppLanguage } from "@/modules/meal-planning/presentation/hooks/useDinneroStore";

export const PRODUCT_COPY = {
  en: {
    nav: ["Tonight", "Week", "Me"],
    common: { back: "Back", close: "Close", swap: "Swap", continue: "Continue with Sera" },
    shell: { loading: "Planning your dinners.", offline: "Your meal plan is available offline. Reconnect to refresh the latest dinners.", ready: "Your meal plan is ready." },
    onboarding: {
      progress: "Sera", kicker: "Sera meal planner", continue: "Continue", compose: "Compose the week",
      loadingTitle: "Composing the week.", loadingPhrases: ["Reading your market rhythm...", "Balancing budget and taste...", "Choosing dinners with restraint...", "Arranging a calm shopping guide...", "Preparing the week."],
      shopTitle: "Where do you usually shop?", shopBody: "We tune prices around your real market, not a generic grocery guess.",
      budgetTitle: "What is your maximum dinner budget?", budgetBody: "Pick the weekly ceiling. Sera will plan below it where possible.", budgetLabel: "Weekly maximum", budgetHelper: "Sera uses this as the upper limit for the full dinner week.",
      peopleTitle: "How many people eat at your table?", peopleBody: "Portions, leftovers and quantities follow the size of the table.", person: "person", people: "people",
      goalTitle: "What should the week prioritize?", goalBody: "Pick the mood of the plan; Sera will curate around it.",
      vibeTitle: "What style feels right?", vibeBody: "Choose up to 3. Selected: {count}/3",
      dietTitle: "Any dietary needs?", dietBody: "Sera will respect these boundaries.",
      timeTitle: "How much time do you have?", timeBody: "No elaborate recipes on rushed evenings.",
      kitchenTitle: "What is already in your kitchen?", kitchenBody: "Use what is there first.",
      batchCooking: "I cook the whole week in one batch",
      goalCards: {
        "Save money": { title: "Save money", body: "A week built around value and reuse." },
        "Eat healthier": { title: "Eat healthier", body: "Balanced dinners with fresher choices." },
        "Lose weight": { title: "Lose weight", body: "Lighter meals without feeling clinical." },
        "High protein": { title: "High protein", body: "More satisfying protein-led dinners." },
        "Family meals": { title: "Family meals", body: "Comfortable plates for the whole table." },
        "Quick dinners": { title: "Quick dinners", body: "Low-friction evenings, fewer steps." },
        "Reduce food waste": { title: "Reduce waste", body: "Use what you buy across the week." },
      },
      cookingTimeCards: {
        "15 min": ["15", "Fast pantry dinners"], "30 min": ["30", "Weeknight rhythm"], "45 min": ["45", "A little more care"], "60 min": ["60", "Slow evening cooking"], "No limit": ["No limit", "Let Sera choose freely"],
      },
    },
    marketSections: { Vegetables: ["Vegetables", "Market Fresh"], "Meat & Fish": ["Meat & Fish", "The Counter"], Dairy: ["Dairy", "From the Fridge"], Pantry: ["Pantry", "Kitchen Essentials"], Frozen: ["Frozen", "For Later"], Spices: ["Spices", "Aromatic Shelf"], Other: ["Other", "Last Details"] },
    dashboard: {
      statusFree: "Free", statusPro: "Pro", kicker: "Italian dinner journal",
      title: "A quieter way to plan the week.", compose: "Compose", newWeek: "New week",
      current: "Current journal", noPlan: "No plan", week: "This week", dinners: "dinners",
      market: "market", saved: "saved", empty: "Start with a few preferences. Sera will turn them into a full dinner week.",
      marketKicker: "Market", shoppingGuide: "Shopping guide",
    },
    tonight: { kicker: "Tonight", title: "One clear dinner.", noPlan: "No dinner planned yet.", startWeek: "Plan the week", start: "Start", tired: "Too tired", cooked: "I cooked it", skipped: "Skip tonight", week: "Week", market: "Shopping list", backupTitle: "Plan B", backupBody: "Choose the quickest dinner this week and move the rest forward.", marketBody: "Check ingredients and view your market guide." },
    weekView: { kicker: "This week", title: "The week, gently held.", empty: "Plan a week first.", newWeek: "New week", market: "Shopping list", cooked: "cooked", planned: "planned", skipped: "skipped", done: "Cooked", skip: "Skip", previous: "Previous weeks", dragHint: "Drag meals to swap days. Cooked meals stay fixed.", open: "Open", today: "Today" },
    profile: { kicker: "Sera profile", title: "Your kitchen settings.", demo: "Demo session", account: "Create profile", accountBody: "Sync history, preferences and reminders when account creation is enabled.", language: "Language", country: "Country", budget: "Default budget", people: "Table size", subscription: "Subscription", manage: "Manage membership", legal: "Legal pages", notifications: "Notifications" },
    results: {
      emptyKicker: "Sera Journal", emptyTitle: "Your table is still empty.",
      emptyBody: "Begin with your tastes and budget. Sera will compose the week.", start: "Start planning",
      loadingTitle: "Composing your week.", loadingBody: "A calmer menu is being assembled.",
      journal: "Sera weekly journal", title: "Dinner, curated.", guest: "guest", guests: "guests",
      estimated: "Estimated market", budget: "Budget", budgetMax: "Budget max", inRange: "In range", watch: "Watch list",
      marketList: "Market list", regenerate: "Regenerate menu", save: "Save plan", evenings: "Seven evenings",
    },
    shopping: {
      emptyTitle: "No market list yet.", emptyBody: "Create a weekly plan and Sera will arrange your ingredients by market section.",
      compose: "Compose the week", guide: "Sera market guide", titleA: "One trip.", titleB: "Everything needed.",
      gathered: "gathered", collected: "Collected", remaining: "Remaining", total: "Total",
      exported: "Exported", export: "Export", tryAgain: "Try again", clear: "Clear", all: "All", items: "items",
      exportTitle: "Sera market list", estimatedTotal: "Estimated total",
    },
    pricing: {
      kicker: "Sera membership", title: "A more graceful kitchen rhythm.", active: "Active", monthly: "Monthly",
      cancel: "Cancel online whenever the season changes.", member: "Member", pro: "Pro", pause: "Demo: pause membership",
      unlock: "Demo: unlock membership", payments: "Payments are processed by Lemon Squeezy. By continuing, you agree to the terms and cancellation policy.",
      links: "Privacy, terms and cancellation", features: ["Unlimited weekly dinner journals", "Unlimited meal swaps", "Saved menus and favourite recipes", "Exportable market guide", "Budget history for calmer shopping", "Family portions and pantry-aware planning"],
    },
    meal: { time: "Time", energy: "Energy", cost: "Cost", why: "Why it belongs here", ingredients: "Ingredients", mainIngredients: "Main ingredients", seasonings: "Pantry & seasonings", method: "Method", preparing: "Sera is preparing the recipe details…", unavailable: "Recipe details will be retried when you reopen Sera.", cookedLocked: "Cooked meals cannot be replaced." },
    paywall: {
      kicker: "Sera membership", title: "Save this week for later.",
      body: "Keep your dinner journal, reopen past weeks, and build a calmer rhythm Sunday after Sunday.",
      perMonth: "/ month", unlock: "Demo: unlock membership",
      subscribe: "Start Membership",
      trial: "Continue with 7-day trial",
      benefits: ["Saved dinner journals", "Previous weeks always available", "Unlimited new weekly plans", "Unlimited refined meal swaps"],
    },
    paywallRegenerate: {
      kicker: "Sera membership", title: "Endless culinary inspiration.",
      body: "You've refined this week's plan multiple times. Start your membership to unlock unlimited recipe regenerations and compose the perfect weekly menu.",
      perMonth: "/ month", unlock: "Demo: unlock membership",
      subscribe: "Start Membership",
      trial: "Continue with 7-day trial",
      benefits: ["Unlimited weekly menu regenerations", "Refine as many times as you like", "Access the entire premium recipe book", "Custom portion scaling & pantry mode"],
    },
    notifications: {
      kicker: "Notifications", on: "Dinner reminders are on.", off: "Let Sera remind you.",
      blocked: "Notifications are blocked in your browser settings.", body: "Get a quiet nudge when your weekly market guide is ready.",
      disable: "Disable notifications", enable: "Enable notifications",
    },
  },
  fr: {
    nav: ["Ce soir", "Semaine", "Moi"],
    common: { back: "Retour", close: "Fermer", swap: "Remplacer", continue: "Continuer avec Sera" },
    shell: { loading: "Planification de tes diners.", offline: "Ton plan repas est disponible hors ligne. Reconnecte-toi pour actualiser les derniers diners.", ready: "Ton plan repas est pret." },
    onboarding: {
      progress: "Sera", kicker: "Planificateur repas Sera", continue: "Continuer", compose: "Composer la semaine",
      loadingTitle: "Composition de la semaine.", loadingPhrases: ["Lecture de ton rythme courses...", "Equilibre budget et envies...", "Selection de diners realistes...", "Organisation du guide courses...", "Preparation de la semaine."],
      shopTitle: "Ou fais-tu tes courses ?", shopBody: "Nous ajustons les prix autour de ton vrai magasin, pas d'une estimation generique.",
      budgetTitle: "Quel est ton budget diner maximum ?", budgetBody: "Choisis le plafond hebdomadaire. Sera planifie en dessous quand c'est possible.", budgetLabel: "Maximum semaine", budgetHelper: "Sera utilise ce montant comme limite haute pour toute la semaine de diners.",
      peopleTitle: "Combien de personnes mangent a table ?", peopleBody: "Portions, restes et quantites suivent la taille de la table.", person: "personne", people: "personnes",
      goalTitle: "Quelle priorite pour la semaine ?", goalBody: "Choisis l'intention du plan; Sera compose autour.",
      vibeTitle: "Quel style te parle ?", vibeBody: "Choisis jusqu'a 3. Selection: {count}/3",
      dietTitle: "Des besoins alimentaires ?", dietBody: "Sera respectera ces limites.",
      timeTitle: "Combien de temps as-tu ?", timeBody: "Pas de recettes compliquees les soirs presses.",
      kitchenTitle: "Qu'as-tu deja en cuisine ?", kitchenBody: "On utilise d'abord ce qui est la.",
      batchCooking: "Je cuisine toute la semaine d'un coup",
      goalCards: {
        "Save money": { title: "Economiser", body: "Une semaine pensee valeur et reutilisation." },
        "Eat healthier": { title: "Manger plus sain", body: "Des diners equilibres et plus frais." },
        "Lose weight": { title: "Alleger", body: "Des plats plus legers sans ton clinique." },
        "High protein": { title: "Plus de proteines", body: "Des diners rassasiants et proteines." },
        "Family meals": { title: "Repas famille", body: "Des assiettes simples pour toute la table." },
        "Quick dinners": { title: "Diners rapides", body: "Moins d'etapes les soirs presses." },
        "Reduce food waste": { title: "Moins gaspiller", body: "Reutiliser les achats sur la semaine." },
      },
      cookingTimeCards: {
        "15 min": ["15", "Diners tres rapides"], "30 min": ["30", "Rythme de semaine"], "45 min": ["45", "Un peu plus soigne"], "60 min": ["60", "Cuisine plus lente"], "No limit": ["Sans limite", "Sera choisit librement"],
      },
    },
    marketSections: { Vegetables: ["Legumes", "Frais du marche"], "Meat & Fish": ["Viande & poisson", "Le comptoir"], Dairy: ["Frais", "Du refrigerateur"], Pantry: ["Epicerie", "Essentiels cuisine"], Frozen: ["Surgeles", "Pour plus tard"], Spices: ["Epices", "Etagere aromatique"], Other: ["Autres", "Derniers details"] },
    dashboard: {
      statusFree: "Gratuit", statusPro: "Pro", kicker: "Journal de diners italien",
      title: "Une facon plus calme de planifier la semaine.", compose: "Composer", newWeek: "Nouvelle semaine",
      current: "Journal actuel", noPlan: "Aucun plan", week: "Cette semaine", dinners: "diners",
      market: "courses", saved: "sauves", empty: "Commence par quelques preferences. Sera les transforme en semaine de diners.",
      marketKicker: "Marche", shoppingGuide: "Guide courses",
    },
    tonight: { kicker: "Ce soir", title: "Un diner clair.", noPlan: "Aucun diner planifie.", startWeek: "Planifier la semaine", start: "Commencer", tired: "Trop fatiguee", cooked: "Je l'ai cuisine", skipped: "Sauter ce soir", week: "Semaine", market: "Liste courses", backupTitle: "Plan B", backupBody: "Choisis le diner le plus rapide de la semaine et garde le reste pour plus tard.", marketBody: "Vérifie tes ingrédients et ton guide courses." },
    weekView: { kicker: "Cette semaine", title: "La semaine, sans pression.", empty: "Planifie d'abord une semaine.", newWeek: "Nouvelle semaine", market: "Liste courses", cooked: "cuisines", planned: "prevu", skipped: "saute", done: "Cuisine", skip: "Sauter", previous: "Semaines precedentes", dragHint: "Glisse les repas pour echanger les jours. Les plats cuisines restent fixes.", open: "Ouvrir", today: "Aujourd'hui" },
    profile: { kicker: "Profil Sera", title: "Tes reglages cuisine.", demo: "Session demo", account: "Creer un profil", accountBody: "Synchronise historique, preferences et rappels quand la creation de compte sera active.", language: "Langue", country: "Pays", budget: "Budget par defaut", people: "Taille de table", subscription: "Abonnement", manage: "Gerer l'abonnement", legal: "Pages legales", notifications: "Notifications" },
    results: {
      emptyKicker: "Journal Sera", emptyTitle: "Ta table est encore vide.",
      emptyBody: "Commence par tes gouts et ton budget. Sera compose la semaine.", start: "Commencer",
      loadingTitle: "Composition de ta semaine.", loadingBody: "Un menu plus calme est en preparation.",
      journal: "Journal hebdomadaire Sera", title: "Diners, selectionnes.", guest: "personne", guests: "personnes",
      estimated: "Courses estimees", budget: "Budget", budgetMax: "Budget maximum", inRange: "Dans la limite", watch: "A surveiller",
      marketList: "Liste courses", regenerate: "Regenerer le menu", save: "Enregistrer le plan", evenings: "Sept soirs",
    },
    shopping: {
      emptyTitle: "Pas encore de liste courses.", emptyBody: "Cree une semaine et Sera classera tes ingredients par rayon.",
      compose: "Composer la semaine", guide: "Guide marche Sera", titleA: "Une sortie.", titleB: "Tout ce qu'il faut.",
      gathered: "pris", collected: "Pris", remaining: "Restant", total: "Total",
      exported: "Exporte", export: "Exporter", tryAgain: "Reessayer", clear: "Vider", all: "Tout", items: "articles",
      exportTitle: "Liste courses Sera", estimatedTotal: "Total estime",
    },
    pricing: {
      kicker: "Abonnement Sera", title: "Un rythme cuisine plus elegant.", active: "Actif", monthly: "Mensuel",
      cancel: "Annule en ligne a tout moment.", member: "Membre", pro: "Pro", pause: "Demo : suspendre",
      unlock: "Demo : debloquer", payments: "Paiements traites par Lemon Squeezy. En continuant, tu acceptes les conditions et la politique d'annulation.",
      links: "Confidentialite, conditions et annulation", features: ["Semaines de diners illimitees", "Remplacements illimites", "Menus sauvegardes", "Guide courses exportable", "Historique budget", "Portions famille et placard pris en compte"],
    },
    meal: { time: "Temps", energy: "Energie", cost: "Cout", why: "Pourquoi ce plat", ingredients: "Ingredients", mainIngredients: "Ingredients du plat", seasonings: "Fond de placard & assaisonnements", method: "Methode", preparing: "Sera prepare les details de la recette…", unavailable: "Les details seront relances a la prochaine ouverture de Sera.", cookedLocked: "Un plat deja cuisine ne peut pas etre remplace." },
    paywall: {
      kicker: "Abonnement Sera", title: "Sauvegarde cette semaine.",
      body: "Garde ton journal de diners, retrouve les semaines passees et construis un rythme plus calme dimanche apres dimanche.",
      perMonth: "/ mois", unlock: "Demo : debloquer",
      subscribe: "S'abonner à Sera",
      trial: "Continuer avec l'essai de 7 jours",
      benefits: ["Journaux de diners sauvegardes", "Semaines precedentes toujours accessibles", "Nouvelles semaines illimitees", "Remplacements raffines illimites"],
    },
    paywallRegenerate: {
      kicker: "Abonnement Sera",
      title: "Une inspiration culinaire sans fin.",
      body: "Tu as personnalise le plan de cette semaine plusieurs fois. Rejoins Sera Pro pour deverrouiller les regenerations illimitees et composer le menu parfait.",
      perMonth: "/ mois", unlock: "Demo : debloquer",
      subscribe: "S'abonner à Sera",
      trial: "Continuer avec l'essai de 7 jours",
      benefits: ["Regenerations de menus illimitees", "Personnalise ton menu a l'infini", "Accede a l'integralite du livre de recettes", "Portions sur mesure et mode placard"],
    },
    notifications: {
      kicker: "Notifications", on: "Les rappels diner sont actifs.", off: "Laisse Sera te le rappeler.",
      blocked: "Les notifications sont bloquees dans ton navigateur.", body: "Recois un rappel discret quand ton guide courses est pret.",
      disable: "Desactiver les notifications", enable: "Activer les notifications",
    },
  },
  it: {
    nav: ["Stasera", "Settimana", "Io"],
    common: { back: "Indietro", close: "Chiudi", swap: "Cambia", continue: "Continua con Sera" },
    shell: { loading: "Pianificazione delle cene.", offline: "Il tuo piano pasti e disponibile offline. Riconnettiti per aggiornare le ultime cene.", ready: "Il tuo piano pasti e pronto." },
    onboarding: {
      progress: "Sera", kicker: "Pianificatore pasti Sera", continue: "Continua", compose: "Componi la settimana",
      loadingTitle: "Composizione della settimana.", loadingPhrases: ["Lettura del tuo ritmo spesa...", "Equilibrio tra budget e gusto...", "Scelta di cene realistiche...", "Organizzazione della guida spesa...", "Preparazione della settimana."],
      shopTitle: "Dove fai di solito la spesa?", shopBody: "Adattiamo i prezzi al tuo vero supermercato, non a una stima generica.",
      budgetTitle: "Qual e il budget massimo per le cene?", budgetBody: "Scegli il tetto settimanale. Sera pianifica sotto quel limite quando possibile.", budgetLabel: "Massimo settimanale", budgetHelper: "Sera usa questo importo come limite alto per tutta la settimana di cene.",
      peopleTitle: "Quante persone mangiano a tavola?", peopleBody: "Porzioni, avanzi e quantita seguono la dimensione della tavola.", person: "persona", people: "persone",
      goalTitle: "Quale priorita per la settimana?", goalBody: "Scegli l'intenzione del piano; Sera curera il resto.",
      vibeTitle: "Che stile preferisci?", vibeBody: "Scegli fino a 3. Selezionati: {count}/3",
      dietTitle: "Esigenze alimentari?", dietBody: "Sera rispettera questi limiti.",
      timeTitle: "Quanto tempo hai?", timeBody: "Niente ricette elaborate nelle sere di corsa.",
      kitchenTitle: "Cosa hai gia in cucina?", kitchenBody: "Usiamo prima quello che c'e.",
      batchCooking: "Cucino tutta la settimana in una volta",
      goalCards: {
        "Save money": { title: "Risparmiare", body: "Una settimana pensata per valore e riuso." },
        "Eat healthier": { title: "Mangiare meglio", body: "Cene equilibrate e piu fresche." },
        "Lose weight": { title: "Piu leggero", body: "Piatti leggeri senza tono clinico." },
        "High protein": { title: "Piu proteine", body: "Cene sazianti guidate dalle proteine." },
        "Family meals": { title: "Famiglia", body: "Piatti comodi per tutta la tavola." },
        "Quick dinners": { title: "Cene rapide", body: "Sere piu semplici, meno passaggi." },
        "Reduce food waste": { title: "Meno sprechi", body: "Riusa gli acquisti durante la settimana." },
      },
      cookingTimeCards: {
        "15 min": ["15", "Cene molto rapide"], "30 min": ["30", "Ritmo settimanale"], "45 min": ["45", "Un po' piu cura"], "60 min": ["60", "Cucina lenta"], "No limit": ["Senza limite", "Sera sceglie libera"],
      },
    },
    marketSections: { Vegetables: ["Verdure", "Fresco di mercato"], "Meat & Fish": ["Carne & pesce", "Il banco"], Dairy: ["Frigo", "Dal fresco"], Pantry: ["Dispensa", "Essenziali cucina"], Frozen: ["Surgelati", "Per dopo"], Spices: ["Spezie", "Mensola aromatica"], Other: ["Altro", "Ultimi dettagli"] },
    dashboard: {
      statusFree: "Gratis", statusPro: "Pro", kicker: "Diario italiano della cena",
      title: "Un modo piu calmo per pianificare la settimana.", compose: "Componi", newWeek: "Nuova settimana",
      current: "Diario attuale", noPlan: "Nessun piano", week: "Questa settimana", dinners: "cene",
      market: "spesa", saved: "salvati", empty: "Inizia con poche preferenze. Sera le trasforma in una settimana di cene.",
      marketKicker: "Mercato", shoppingGuide: "Guida spesa",
    },
    tonight: { kicker: "Stasera", title: "Una cena chiara.", noPlan: "Nessuna cena pianificata.", startWeek: "Pianifica la settimana", start: "Inizia", tired: "Troppo stanca", cooked: "L'ho cucinato", skipped: "Salta stasera", week: "Settimana", market: "Lista spesa", backupTitle: "Piano B", backupBody: "Scegli la cena piu rapida della settimana e sposta il resto.", marketBody: "Controlla gli ingredienti e vedi la guida spesa." },
    weekView: { kicker: "Questa settimana", title: "La settimana, con calma.", empty: "Pianifica prima una settimana.", newWeek: "Nuova settimana", market: "Lista spesa", cooked: "cucinate", planned: "previsto", skipped: "saltato", done: "Cucinato", skip: "Salta", previous: "Settimane precedenti", dragHint: "Trascina le cene per scambiare i giorni. Le cene cucinate restano fisse.", open: "Apri", today: "Oggi" },
    profile: { kicker: "Profilo Sera", title: "Le tue impostazioni cucina.", demo: "Sessione demo", account: "Crea profilo", accountBody: "Sincronizza storico, preferenze e promemoria quando l'account sara attivo.", language: "Lingua", country: "Paese", budget: "Budget predefinito", people: "Persone a tavola", subscription: "Abbonamento", manage: "Gestisci abbonamento", legal: "Pagine legali", notifications: "Notifiche" },
    results: {
      emptyKicker: "Diario Sera", emptyTitle: "La tua tavola e ancora vuota.",
      emptyBody: "Parti da gusti e budget. Sera compone la settimana.", start: "Inizia",
      loadingTitle: "Composizione della settimana.", loadingBody: "Un menu piu calmo sta prendendo forma.",
      journal: "Diario settimanale Sera", title: "Cene curate.", guest: "persona", guests: "persone",
      estimated: "Spesa stimata", budget: "Budget", budgetMax: "Budget massimo", inRange: "Nel limite", watch: "Da controllare",
      marketList: "Lista spesa", regenerate: "Rigenera menu", save: "Salva piano", evenings: "Sette sere",
    },
    shopping: {
      emptyTitle: "Nessuna lista spesa.", emptyBody: "Crea una settimana e Sera ordinera gli ingredienti per reparto.",
      compose: "Componi la settimana", guide: "Guida mercato Sera", titleA: "Una spesa.", titleB: "Tutto cio che serve.",
      gathered: "presi", collected: "Presi", remaining: "Restante", total: "Totale",
      exported: "Esportata", export: "Esporta", tryAgain: "Riprova", clear: "Svuota", all: "Tutto", items: "articoli",
      exportTitle: "Lista spesa Sera", estimatedTotal: "Totale stimato",
    },
    pricing: {
      kicker: "Abbonamento Sera", title: "Un ritmo in cucina piu elegante.", active: "Attivo", monthly: "Mensile",
      cancel: "Annulla online quando vuoi.", member: "Membro", pro: "Pro", pause: "Demo: sospendi",
      unlock: "Demo: sblocca", payments: "Pagamenti gestiti da Lemon Squeezy. Continuando accetti termini e cancellazione.",
      links: "Privacy, termini e cancellazione", features: ["Diari settimanali illimitati", "Cambi pasto illimitati", "Menu salvati", "Guida spesa esportabile", "Storico budget", "Porzioni famiglia e dispensa"],
    },
    meal: { time: "Tempo", energy: "Energia", cost: "Costo", why: "Perche questo piatto", ingredients: "Ingredienti", mainIngredients: "Ingredienti principali", seasonings: "Condimenti e dispensa", method: "Metodo", preparing: "Sera sta preparando i dettagli della ricetta…", unavailable: "I dettagli saranno riprovati alla prossima apertura di Sera.", cookedLocked: "Una cena gia cucinata non puo essere sostituita." },
    paywall: {
      kicker: "Abbonamento Sera", title: "Salva questa settimana.",
      body: "Conserva il tuo diario delle cene, riapri le settimane passate e costruisci un ritmo piu calmo domenica dopo domenica.",
      perMonth: "/ mese", unlock: "Demo: sblocca",
      subscribe: "Abbonati a Sera",
      trial: "Continua con la prova di 7 giorni",
      benefits: ["Diari cena salvati", "Settimane precedenti sempre disponibili", "Nuove settimane illimitate", "Cambi pasto raffinati illimitati"],
    },
    paywallRegenerate: {
      kicker: "Abbonamento Sera",
      title: "Ispirazione culinaria senza limiti.",
      body: "Hai personalizzato il piano di questa settimana piu volte. Abbonati a Sera Pro per sbloccare rigenerazioni illimitate e comporre il menu settimanale perfetto.",
      perMonth: "/ mese", unlock: "Demo: sblocca",
      subscribe: "Abbonati a Sera",
      trial: "Continua con la prova di 7 giorni",
      benefits: ["Rigenerazioni menu illimitate", "Personalizza il tuo piano all'infinito", "Accedi all'intero ricettario premium", "Porzioni su misura e dispensa intelligente"],
    },
    notifications: {
      kicker: "Notifiche", on: "Promemoria cena attivi.", off: "Lascia che Sera te lo ricordi.",
      blocked: "Le notifiche sono bloccate nel browser.", body: "Ricevi un promemoria discreto quando la guida spesa e pronta.",
      disable: "Disattiva notifiche", enable: "Attiva notifiche",
    },
  },
} as const;

export function getProductCopy(language: AppLanguage) {
  return PRODUCT_COPY.en;
}
