export interface MockRecipe {
  title: string;
  description: string;
  baseCost: number;
  calories: number;
  prepTime: number;
  isVegetarian: boolean;
  isVegan: boolean;
  isGlutenFree: boolean;
  isLactoseFree: boolean;
  isHalal: boolean;
  isPescatarian: boolean;
  ingredients: { name: string; category: string; baseQty: string; basePrice: number }[];
  steps: string[];
  reasons: string[];
}

export const RECIPE_LIBRARY: MockRecipe[] = [
  {
    title: "Tomato Tuna Pasta",
    description: "A quick budget-friendly pasta using pantry ingredients and canned tuna.",
    baseCost: 3.5,
    calories: 620,
    prepTime: 20,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isLactoseFree: true,
    isHalal: false,
    isPescatarian: true,
    ingredients: [
      { name: "Pasta", category: "Pantry", baseQty: "200g", basePrice: 0.4 },
      { name: "Canned tuna", category: "Meat & Fish", baseQty: "160g", basePrice: 2.2 },
      { name: "Tomato sauce", category: "Pantry", baseQty: "250g", basePrice: 0.6 },
      { name: "Onion", category: "Vegetables", baseQty: "1", basePrice: 0.2 },
      { name: "Olive oil", category: "Pantry", baseQty: "20ml", basePrice: 0.1 },
    ],
    steps: [
      "Boil water in a large pot and cook the pasta according to package instructions.",
      "In a pan, heat olive oil and saute finely chopped onion until soft.",
      "Add drained canned tuna and tomato sauce to the pan. Simmer for 10 minutes.",
      "Drain pasta, toss it into the sauce, and serve hot.",
    ],
    reasons: ["Uses pasta and canned tuna from your pantry", "Ready in under 20 minutes", "Keeps the weekly plan affordable"],
  },
  {
    title: "Chicken Zucchini Rice Bowl",
    description: "Lean chicken breast sauteed with fresh zucchini served over rice.",
    baseCost: 4.8,
    calories: 550,
    prepTime: 30,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isHalal: true,
    isPescatarian: false,
    ingredients: [
      { name: "Rice", category: "Pantry", baseQty: "150g", basePrice: 0.5 },
      { name: "Chicken breast", category: "Meat & Fish", baseQty: "250g", basePrice: 3 },
      { name: "Zucchini", category: "Vegetables", baseQty: "200g", basePrice: 0.8 },
      { name: "Olive oil", category: "Pantry", baseQty: "20ml", basePrice: 0.1 },
      { name: "Garlic", category: "Vegetables", baseQty: "1 clove", basePrice: 0.4 },
    ],
    steps: [
      "Cook rice in boiling salted water.",
      "Cut chicken breast and zucchini into bite-sized cubes.",
      "Saute garlic in olive oil, then add chicken and cook until golden.",
      "Add zucchini and cook for another 8-10 minutes. Mix with rice and enjoy.",
    ],
    reasons: ["High in protein to support your goal", "Features healthy fresh vegetables", "Gluten-free friendly recipe"],
  },
  {
    title: "Rustic Lentil Soup",
    description: "A warm, comforting soup made with brown lentils, carrots, and potatoes.",
    baseCost: 2.8,
    calories: 420,
    prepTime: 35,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isHalal: true,
    isPescatarian: true,
    ingredients: [
      { name: "Brown lentils", category: "Pantry", baseQty: "200g", basePrice: 0.7 },
      { name: "Carrot", category: "Vegetables", baseQty: "1", basePrice: 0.3 },
      { name: "Potatoes", category: "Vegetables", baseQty: "200g", basePrice: 0.6 },
      { name: "Tomato sauce", category: "Pantry", baseQty: "100g", basePrice: 0.3 },
      { name: "Onion", category: "Vegetables", baseQty: "1", basePrice: 0.2 },
      { name: "Garlic", category: "Vegetables", baseQty: "1 clove", basePrice: 0.4 },
      { name: "Olive oil", category: "Pantry", baseQty: "20ml", basePrice: 0.3 },
    ],
    steps: [
      "Chop onion, garlic, and carrot. Dice the potato.",
      "Saute onion, garlic, and carrot in olive oil in a deep pot.",
      "Add potatoes, lentils, tomato sauce, and 800ml of water.",
      "Simmer for 25-30 minutes until lentils and potatoes are tender.",
    ],
    reasons: ["Uses lentils and onion already in your kitchen", "Very cheap eats that lower your total grocery bill", "Rich in fiber and 100% vegan"],
  },
  {
    title: "Vegetable Frittata",
    description: "An Italian classic egg dish baked with onions, spinach, and potatoes.",
    baseCost: 3.2,
    calories: 480,
    prepTime: 20,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isHalal: true,
    isPescatarian: true,
    ingredients: [
      { name: "Eggs", category: "Dairy", baseQty: "4", basePrice: 1.2 },
      { name: "Potatoes", category: "Vegetables", baseQty: "150g", basePrice: 0.5 },
      { name: "Frozen vegetables", category: "Frozen", baseQty: "150g", basePrice: 1 },
      { name: "Onion", category: "Vegetables", baseQty: "1", basePrice: 0.2 },
      { name: "Olive oil", category: "Pantry", baseQty: "15ml", basePrice: 0.3 },
    ],
    steps: [
      "Thinly slice potatoes and onion.",
      "Heat olive oil in a frying pan and cook potato slices and onion until soft.",
      "Beat eggs in a bowl with a pinch of salt. Pour over potatoes and frozen vegetables.",
      "Cook on medium heat until the bottom is set, flip, and cook the other side.",
    ],
    reasons: ["Ready in 20 minutes for a quick dinner", "Reuses potatoes from other meals", "High protein vegetarian option"],
  },
  {
    title: "Pasta al Pesto",
    description: "Classic Italian pasta tossed with fragrant green basil pesto sauce.",
    baseCost: 2.9,
    calories: 590,
    prepTime: 15,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLactoseFree: false,
    isHalal: true,
    isPescatarian: true,
    ingredients: [
      { name: "Pasta", category: "Pantry", baseQty: "200g", basePrice: 0.4 },
      { name: "Pesto sauce", category: "Pantry", baseQty: "90g", basePrice: 1.8 },
      { name: "Cheese", category: "Dairy", baseQty: "30g", basePrice: 0.7 },
    ],
    steps: ["Boil pasta in salted water.", "Drain pasta, reserving a couple of tablespoons of cooking water.", "Mix pasta with pesto and reserved water. Top with grated cheese."],
    reasons: ["Super quick meal ready in 15 minutes", "Italian comfort food favorite", "Highly affordable pantry dish"],
  },
  {
    title: "Potato Tuna Salad",
    description: "A refreshing dinner salad with boiled potatoes, canned tuna, and beans.",
    baseCost: 4,
    calories: 510,
    prepTime: 25,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isHalal: false,
    isPescatarian: true,
    ingredients: [
      { name: "Potatoes", category: "Vegetables", baseQty: "250g", basePrice: 0.8 },
      { name: "Canned tuna", category: "Meat & Fish", baseQty: "160g", basePrice: 2.2 },
      { name: "Beans", category: "Pantry", baseQty: "200g", basePrice: 0.8 },
      { name: "Olive oil", category: "Pantry", baseQty: "10ml", basePrice: 0.2 },
    ],
    steps: ["Boil whole potatoes until soft, then peel and dice.", "Drain the canned tuna and beans.", "Toss potatoes, tuna, and beans in a serving bowl.", "Drizzle with olive oil, salt, and pepper. Serve cold."],
    reasons: ["Uses potatoes already in your inventory", "No complex cooking required", "Perfect balanced Mediterranean diet meal"],
  },
  {
    title: "Chickpea Tomato Stew",
    description: "A hearty vegetarian stew with chickpeas, canned tomatoes, and spices.",
    baseCost: 3.1,
    calories: 450,
    prepTime: 25,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isHalal: true,
    isPescatarian: true,
    ingredients: [
      { name: "Beans", category: "Pantry", baseQty: "240g", basePrice: 0.8 },
      { name: "Tomato sauce", category: "Pantry", baseQty: "400g", basePrice: 1 },
      { name: "Garlic", category: "Vegetables", baseQty: "2 cloves", basePrice: 0.8 },
      { name: "Onion", category: "Vegetables", baseQty: "1", basePrice: 0.2 },
      { name: "Spices", category: "Spices", baseQty: "1 pinch", basePrice: 0.3 },
    ],
    steps: ["Saute chopped onion and garlic in a pot with olive oil.", "Add tomato sauce, chickpeas, and spices.", "Simmer for 15 minutes to allow flavors to combine.", "Serve hot with toasted bread if desired."],
    reasons: ["Zero waste recipe reusing beans and tomatoes", "Rich in plant-based proteins", "Low prep time and budget friendly"],
  },
  {
    title: "Tuna Rice Salad",
    description: "A cold rice salad mixed with tuna, sweet corn, and frozen peas.",
    baseCost: 3.8,
    calories: 530,
    prepTime: 20,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isHalal: false,
    isPescatarian: true,
    ingredients: [
      { name: "Rice", category: "Pantry", baseQty: "150g", basePrice: 0.5 },
      { name: "Canned tuna", category: "Meat & Fish", baseQty: "80g", basePrice: 1.1 },
      { name: "Frozen vegetables", category: "Frozen", baseQty: "150g", basePrice: 1 },
      { name: "Olive oil", category: "Pantry", baseQty: "15ml", basePrice: 0.3 },
      { name: "Yogurt", category: "Dairy", baseQty: "50g", basePrice: 0.9 },
    ],
    steps: ["Boil rice, adding frozen peas in the last 5 minutes.", "Drain and rinse with cold water.", "Toss with drained tuna, corn, olive oil, and yogurt for creaminess."],
    reasons: ["Ready in 20 minutes", "Refreshing and high-protein salad", "Utilizes pantry tuna and frozen items"],
  },
  {
    title: "Pasta e Fagioli",
    description: "Traditional Italian pasta and bean soup, thick and nutritious.",
    baseCost: 2.6,
    calories: 580,
    prepTime: 30,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isHalal: true,
    isPescatarian: true,
    ingredients: [
      { name: "Pasta", category: "Pantry", baseQty: "150g", basePrice: 0.3 },
      { name: "Beans", category: "Pantry", baseQty: "240g", basePrice: 0.8 },
      { name: "Tomato sauce", category: "Pantry", baseQty: "100g", basePrice: 0.3 },
      { name: "Onion", category: "Vegetables", baseQty: "1", basePrice: 0.2 },
      { name: "Olive oil", category: "Pantry", baseQty: "10ml", basePrice: 0.2 },
      { name: "Spices", category: "Spices", baseQty: "1 pinch", basePrice: 0.2 },
    ],
    steps: ["Saute chopped onion in olive oil.", "Add tomato sauce, drained beans, spices, and 500ml water. Simmer 10 minutes.", "Mash some beans to thicken the broth, add pasta directly into the pot.", "Cook until pasta is al dente, stirring frequently."],
    reasons: ["Traditional Italian budget staple", "Uses affordable canned beans and pasta", "Very low waste and high fiber"],
  },
];
